export { default as P5Button } from './button/button.vue'
export { default as P5Title } from './title/title.vue'
export { default as P5Divider } from './divider/divider.vue'
export { default as P5Input } from './input/input.vue'
export { default as P5Switch } from './switch/switch.vue'
export { default as P5Slider } from './slider/slider.vue'
