export { default as P5Button } from './button/button.vue'
export { default as P5Title } from './title/title.vue'
export { default as P5Divider } from './divider/divider.vue'
export { default as P5Switch } from './switch/switch.vue'
export { default as P5Slider } from './slider/slider.vue'
export { default as P5Text } from './text/text.vue'
export { default as P5BackTop } from './backTop/backTop.vue'
export { default as P5Table } from './table/table.vue'
export { default as P5TableItem } from './table/tableItem.vue'
export { default as P5Icon } from './icon/icon.vue'
export { default as P5Crowd } from './canvas/crowd/crowd.vue'
export { default as P5Upload } from './upload/upload.vue'

